export const Users = [
	{
		id: 1,
		profilePicture: 'assets/person/person.jpeg',
		username: 'Joe Biden',
	},
	{
		id: 2,
		profilePicture: 'assets/person/person2.jpeg',
		username: 'Janell Shrum',
	},
	{
		id: 3,
		profilePicture: 'assets/person/person3.jpeg',
		username: 'Alex Durden',
	},
	{
		id: 4,
		profilePicture: 'assets/person/person4.jpeg',
		username: 'Dora Hawks',
	},
	{
		id: 5,
		profilePicture: 'assets/person/person5.jpeg',
		username: 'Thomas Holden',
	},
	{
		id: 6,
		profilePicture: 'assets/person/person6.jpeg',
		username: 'Shirley Beauchamp',
	},
	{
		id: 7,
		profilePicture: 'assets/person/person7.jpeg',
		username: 'Travis Bennett',
	},
	{
		id: 8,
		profilePicture: 'assets/person/person8.jpeg',
		username: 'Kristen Thomas',
	},
	{
		id: 9,
		profilePicture: 'assets/person/person9.jpeg',
		username: 'Gary Duty',
	},
	{
		id: 10,
		profilePicture: 'assets/person/person10.jpeg',
		username: 'Maria Sonie',
	},
];

export const Posts = [
	{
		id: 1,
		desc: 'Love For All, Hatred For None.',
		photo: 'assets/posts/post1.jpeg',
		date: '5 mins ago',
		userId: 1,
		like: 32,
		comment: 9,
	},
	{
		id: 2,
		photo: 'assets/posts/post2.jpeg',
		date: '15 mins ago',
		userId: 2,
		like: 2,
		comment: 1,
	},
	{
		id: 3,
		desc: 'Every moment is a fresh beginning.',
		photo: 'assets/posts/post3.jpeg',
		date: '1 hour ago',
		userId: 3,
		like: 61,
		comment: 2,
	},
	{
		id: 4,
		photo: 'assets/posts/post4.jpeg',
		date: '4 hours ago',
		userId: 4,
		like: 7,
		comment: 3,
	},
	{
		id: 5,
		photo: 'assets/posts/post5.jpeg',
		date: '5 hours ago',
		userId: 5,
		like: 23,
		comment: 5,
	},
	{
		id: 6,
		photo: 'assets/posts/post6.jpeg',
		date: '1 day ago',
		userId: 6,
		like: 44,
		comment: 6,
	},
	{
		id: 7,
		desc: 'Never regret anything that made you smile.',
		photo: 'assets/posts/post7.jpeg',
		date: '2 days ago',
		userId: 7,
		like: 52,
		comment: 3,
	},
	{
		id: 8,
		photo: 'assets/posts/post8.jpeg',
		date: '3 days ago',
		userId: 8,
		like: 15,
		comment: 1,
	},
	{
		id: 9,
		desc: 'Change the world by being yourself.',
		photo: 'assets/posts/post9.jpeg',
		date: '5 days ago',
		userId: 9,
		like: 11,
		comment: 2,
	},
	{
		id: 10,
		photo: 'assets/posts/post10.jpeg',
		date: '1 week ago',
		userId: 10,
		like: 104,
		comment: 12,
	},
];
